### ISSUE TITLE
What is the purpose of this dataset? What does it?

### ISSUE THREAD

**Issue by ardaltunyay** [bluenex/WekaLearningDataset#1]
(Bank dataset)
I didn't understand what the data set was doing. What's the meaning of pep? I thought it was program evaluation procedures. Is it correct?

**Comment by bluenex** [comment]
I'm not sure either what does _pep_ mean. But the Bank Dataset is used in classification tutorial on Weka that I was learning at the time. The purpose of this repo is to collect incomplete data used in that tutorial in one place. However, I didn't document what tutorial or how I used it publicly, because I did it internally. 😄
